version: '3.8'

services:
  nginx:
    build:
      context: ../..
      dockerfile: backend/docker/nginx/Dockerfile
    ports:
      - '80:80'
    depends_on:
      - api
    restart: unless-stopped

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: node dist/server.js
    env_file:
      - ../.env
    # environment:
    #   - DATABASE_URL=postgresql://postgres:password@postgres:5432/coding_analytics?sslmode=disable
    #   - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: npm run worker:prod
    env_file:
      - ../.env
    # environment:
    #   - DATABASE_URL=postgresql://postgres:password@postgres:5432/coding_analytics?sslmode=disable
    #   - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - api

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-coding_analytics}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - '6380:6379'
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
